# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fpop_cpp <- function(y, alpha, muMinLocal, muMaxLocal, wt, nbThreads) {
    .Call(`_parallelFpop_fpop_cpp`, y, alpha, muMinLocal, muMaxLocal, wt, nbThreads)
}

